### ISSUE TITLE
Is it working with CI4 ?

### ISSUE THREAD

**Issue by ashisharora-github** [yidas/codeigniter-api-controller#4]

**Comment by yidas** [comment]
This library designs based on Codeigniter 3, which CI4 does not release yet.

**Comment by ashisharora-github** [comment]
Its also not working with CI 3.1.8 ,

i am getting issue 

Message: Class 'CI_Format' not found


Filename: /var/www/html/proofhub_api_v4/system/core/Common.php

**Comment by yidas** [comment]
There has no `CI_Format` used in this library.

Your error message seems that you has an error in your Codeigniter framework, you could check the error bootstrap or provide detail code for debugging.
