### ISSUE TITLE
Add response header?

### ISSUE THREAD

**Issue by zkelo** [yidas/codeigniter-api-controller#6]
Hi!

I need to add a header `Access-Control-Allow-Origin` in response of API. How I can do that?

**Comment by yidas** [comment]
Hi @zkelo,

You can add it with output `set_header()` before return response in a API method:

```php
class ApiController extends yidas\rest\Controller
{
    public function index()
    {
        $this->output->set_header('Access-Control-Allow-Origin: *');

        return $this->response->json(['bar'=>'foo']);
    }
}
```

Cheers.

**Comment by yidas** [comment]
You are mentioning a good point that I will add the header interface into Response component.

**Comment by yidas** [comment]
Hi @zkelo,

Header feature is release from v1.6.1:

https://github.com/yidas/codeigniter-rest#withaddedheader

Cheers

**Comment by zkelo** [comment]
> Hi @zkelo,
> 
> Header feature is release from v1.6.1:
> 
> https://github.com/yidas/codeigniter-rest#withaddedheader
> 
> Cheers

Thanks!

**Comment by zkelo** [comment]
But what if I need to send some headers for every response? Can you add a config file for your controller for adding response headers by default?

**Comment by yidas** [comment]
@zkelo 

You could use constructor to do it:

```php
class ApiController extends yidas\rest\Controller
{
    function __construct()
    {
        $this->response->withAddedHeader('Access-Control-Allow-Origin', '*');
    }
}
```
